export const about = {
  image: "/images/Himanshu_Linkedin.JPG",
  bio: [
    "I started out building robots, not models.",
    "Right after my bachelor's in mechanical engineering, I joined a robotics startup building autonomous mobile robots for healthcare, machines that could navigate hospitals on their own. It was my first real exposure to a hard truth about engineering: the world doesn't behave like a textbook. Sensors disagree with each other. Hallways look different at 3 AM than they did in testing. A system that works perfectly in simulation can still fail the moment it meets something it hasn't seen before. Learning to build for that kind of uncertainty, not around it, shaped how I've approached every problem since.",
    "Somewhere in the middle of that, a different question started pulling at me. Robotics taught me to reason about a machine's uncertainty, its sensors, its physical environment, but I found myself more curious about the uncertainty behind decisions: what the data was actually saying, and what to do about it. I started freelancing as a data scientist on the side, almost as an experiment, and it didn't stay a side interest for long. That pull is what took me to Chalmers for a Master's in Complex Adaptive Systems, a program built for people who didn't want to choose between the two. I kept working in robotics there, but I was building a real foundation in machine learning and AI alongside it, and by the end, the two weren't separate interests anymore. They'd become the same question, asked in different languages: how do you build something that holds up when the real world pushes back?",
    "My thesis is where that question got a real answer. It combined generative AI with real industrial data, and it's what led to a full-time offer at Volvo Group.",
    "Today, I work at the intersection of statistical modeling, machine learning, and generative AI, building enterprise AI systems that go into production, not just proof-of-concept demos. The problems have changed, robots to claims platforms, sensors to enterprise data, but the instinct hasn't: understand the system, deal with the mess real-world data always has, and build something that actually holds up outside a controlled environment.",
    "Beyond my day-to-day work, I stay connected to where it all started: robotics, autonomous navigation, and SLAM are still things I follow and think about.",
  ],
};
