export const skills = {
  languages: ["Python", "SQL", "C++", "Go", "MATLAB", "Linux/Bash"],
  mlAndAi: [
    "TensorFlow",
    "PyTorch",
    "Scikit-Learn",
    "MLflow",
    "Generative AI",
    "LLMs",
    "Prompt Engineering",
    "LangChain",
    "LangGraph",
    "AutoGen",
    "NLP",
    "Computer Vision",
    "GANs",
    "Deep Learning",
    "Predictive Modeling",
    "Time Series Analysis",
    "A/B Testing",
    "Statistics",
    "EDA",
    "Feature Engineering",
  ],
  dataEngineering: [
    "ETL Pipelines",
    "Azure Databricks",
    "Microsoft Azure",
    "AWS",
    "Data Visualization",
    "Power BI",
  ],
  devOpsAndTools: [
    "Docker",
    "Kubernetes",
    "Git",
    "GitHub Actions",
    "CI/CD",
    "FastAPI",
    "Flask",
    "REST APIs",
    "React.js",
    "Agile/Scrum",
    "JIRA",
  ],
  robotics: [
    "ROS",
    "ROS2",
    "SLAM",
    "Gazebo",
    "Motion Planning",
    "Autonomous Navigation",
    "Sensor Fusion",
  ],
  soft: [
    "Stakeholder Management",
    "Cross-functional Collaboration",
    "Problem Solving",
    "Communication",
    "Critical Thinking",
    "Data-Driven Decision Making",
    "Leadership",
  ],
};
